config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
  validates :phone_number, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
  def show
    @restaurant = Restaurant.find(params[:id])
  end
  def new
    @restaurant = Restaurant.new
  end
  def edit
    @restaurants = Restaurant.find(params[:id])
  end
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end
  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path(@restaurant)
  end

private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "Envoyer", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Modifier un restaurant:</h1>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Tous les restaurants:</h1>
<% @restaurants.each do |restaurant| %>
  <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
  <p><%= restaurant.phone_number %></p>
  <p><%= restaurant.address %></p>
  <p><%= restaurant.category %></p>
  <ul>
  <% restaurant.reviews.each do |review|%>
    <li>
      <%= "*" * (review.rating).to_i %>
    </li>
  <% end %>
</ul>
    <%= link_to restaurant_path(restaurant), method: :delete do %>
        <i class="fa fa-trash-alt"></i>
    <% end %>
  <% end %>

<h3><%= link_to "+ Ajouter un restaurant", new_restaurant_path %></h3>

app/views/restaurants/new.html.erb
<h1>Ajouter un restaurant:</h1>
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.category %></p>
<ul>
  <% @restaurant.reviews.each do |review|%>
    <li>
      <%= review.content%>
      <%= "*" * (review.rating).to_i %>
      <%= link_to restaurant_review_path(@restaurant, review), method: :delete do %>
        <i class="fa fa-trash-alt"></i>
      <% end %>
    </li>
  <% end %>
</ul>

<p><%= link_to "Ajouter une review", new_restaurant_review_path(@restaurant), :class => "btn btn-primary"  %><p>
<p><%= link_to "Modifier les infos du restaurant", edit_restaurant_path(@restaurant), :class => "btn btn-info"  %><p>
<p class: btn btn-primary><%= link_to "Home", restaurants_path, :class => "btn btn-warning" %><p>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "+ Ajouter une review", class: "btn btn-primary" %>
<% end %>